const cities = [
  "Dhaka",
  "Chittagong",
  "Rajshahi",
  "Khulna",
  "Barisal",
  "Sylhet",
  "Rangpur",
  "Mymensingh",
];
const districts = [
  "Dhaka",
  "Chittagong",
  "Rajshahi",
  "Khulna",
  "Barisal",
  "Sylhet",
  "Rangpur",
  "Mymensingh",
  "Comilla",
  "Jessore",
  "Narayanganj",
  "Narsingdi",
  "Gazipur",
  "Tangail",
  "Bagerhat",
  "Pabna",
  "Faridpur",
  "Manikganj",
  "Munshiganj",
  "Rajbari",
];

const institutes = [
  "University of Dhaka",
  "Bangladesh University of Engineering and Technology (BUET)",
  "Bangladesh Agricultural University (BAU)",
  "Chittagong University",
  "Rajshahi University",
  "Khulna University",
  "Barisal University",
  "Sylhet Agricultural University",
  "Rangpur University",
  "Mymensingh Agricultural University",
  "Comilla University",
  "Jessore University of Science and Technology",
  "Shahjalal University of Science and Technology",
  "Jahangirnagar University",
  "National University",
  "Islamic University of Technology",
  "International Islamic University Chittagong",
  "East West University",
  "BRAC University",
  "American International University-Bangladesh (AIUB)",
];

const names = [
  "Ahmed",
  "Fatima",
  "Ali",
  "Samiha",
  "Tariq",
  "Nasim",
  "Salma",
  "Shahid",
  "Fariha",
  "Mahmud",
];

const professions = [
  "Teacher",
  "Doctor",
  "Engineer",
  "Lawyer",
  "Software Developer",
  "Business Owner",
  "Accountant",
  "Architect",
  "Journalist",
  "Government Official",
];

const educationTypes = ["General", "Koumi", "Alia"];

const marriageStatus = ["Never Married", "Married", "Widowed", "Divorced"];
const averageMonthlyIncomes = [
  10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000,
];

const skinColors = [
  "Fair",
  "Light",
  "Medium",
  "Olive",
  "Brown",
  "Dark",
  // Add more as needed
];
const datesOfBirth = [
  "1995-01-01",
  "1996-02-01",
  "1997-03-01",
  "1998-04-01",
  "1999-05-01",
  "2000-06-01",
  "2001-07-01",
  "2002-08-01",
  "2003-09-01",
  "2004-10-01",
];

const sessions = [
  "20021-22",
  "20020-21",
  "20019-20",
  "20018-19",
  "20017-18",
  "20016-27",
  "20015-16",
  "20014-15",
];
const upazillas = [
  // Dhaka Division
  "Dhaka Sadar",
  "Nawabganj",
  "Narayanganj",
  "Gazipur Sadar",
  "Manikganj",
  "Munshiganj",
  "Jessore Sadar",
  "Shatkhira Sadar",
  "Khulna Sadar",
  "Barisal Sadar",
  "Patuakhali Sadar",
  "Bhola Sadar",
  "Barguna Sadar",
  "Pirojpur Sadar",
  "Jhenaidah Sadar",
  "Magura Sadar",
  "Chuadanga Sadar",
  "Kushtia Sadar",
  "Meherpur Sadar",
  "Narayanganj Sadar",
  "Faridpur Sadar",
  "Rajbari Sadar",
  "Gopalganj Sadar",
  "Tangail Sadar",
  "Mymensingh Sadar",
  "Sherpur Sadar",
  "Netrokona Sadar",
  "Kishoreganj Sadar",
  "Jamalpur Sadar",
  "Sunamganj Sadar",
  "Sylhet Sadar",
  "Habiganj Sadar",
  "Moulvibazar Sadar",
  "Brahmanbaria Sadar",
  "Comilla Sadar",
  "Chandpur Sadar",
  "Feni Sadar",
  "Noakhali Sadar",
  "Lakshmipur Sadar",
  "Chittagong Sadar",
  "Cox's Bazar Sadar",
  "Rangamati Sadar",
  "Khagrachhari Sadar",
  "Bandarban Sadar",

  // Rangpur Division
  "Dinajpur Sadar",
  "Panchagarh Sadar",
  "Thakurgaon Sadar",
  "Nilphamari Sadar",
  "Gaibandha Sadar",
  "Rangpur Sadar",
  "Kurigram Sadar",
  "Lalmonirhat Sadar",
  "Kurigram Sadar",
  "Lalmonirhat Sadar",
  "Sherpur Sadar",
  "Netrokona Sadar",
  "Kishoreganj Sadar",
  "Jamalpur Sadar",
  "Sunamganj Sadar",
  "Sylhet Sadar",
  "Habiganj Sadar",
  "Moulvibazar Sadar",
  "Brahmanbaria Sadar",
  "Comilla Sadar",
  "Chandpur Sadar",
  "Feni Sadar",
  "Noakhali Sadar",
  "Lakshmipur Sadar",
  "Chittagong Sadar",
  "Cox's Bazar Sadar",
  "Rangamati Sadar",
  "Khagrachhari Sadar",
  "Bandarban Sadar",

  // Mymensingh Division
  "Netrokona Sadar",
  "Kishoreganj Sadar",
  "Jamalpur Sadar",
  "Sunamganj Sadar",
  "Sylhet Sadar",
  "Habiganj Sadar",
  "Moulvibazar Sadar",
  "Brahmanbaria Sadar",
  "Comilla Sadar",
  "Chandpur Sadar",
  "Feni Sadar",
  "Noakhali Sadar",
  "Lakshmipur Sadar",
  "Chittagong Sadar",
  "Cox's Bazar Sadar",
  "Rangamati Sadar",
  "Khagrachhari Sadar",
  "Bandarban Sadar",

  // Chittagong Division
  "Brahmanbaria Sadar",
  "Comilla Sadar",
  "Chandpur Sadar",
  "Feni Sadar",
  "Noakhali Sadar",
  "Lakshmipur Sadar",
  "Chittagong Sadar",
  "Cox's Bazar Sadar",
  "Rangamati Sadar",
  "Khagrachhari Sadar",
  "Bandarban Sadar",

  // Khulna Division
  "Jessore Sadar",
  "Shatkhira Sadar",
  "Khulna Sadar",
  "Barisal Sadar",
  "Patuakhali Sadar",
  "Bhola Sadar",
  "Barguna Sadar",
  "Pirojpur Sadar",
  "Jhenaidah Sadar",
  "Magura Sadar",
  "Chuadanga Sadar",
  "Kushtia Sadar",
  "Meherpur Sadar",

  // Rajshahi Division
  "Pabna Sadar",
  "Sirajganj Sadar",
  "Bogra Sadar",
  "Joypurhat Sadar",
  "Naogaon Sadar",
  "Chapai Nawabganj Sadar",
  "Nawabganj Sadar",
  "Natore Sadar",
  "Kushtia Sadar",
  "Meherpur Sadar",

  // Sylhet Division
  "Sunamganj Sadar",
  "Sylhet Sadar",
  "Habiganj Sadar",
  "Moulvibazar Sadar",

  // Barisal Division
  "Barisal Sadar",
  "Patuakhali Sadar",
  "Bhola Sadar",
  "Barguna Sadar",
  "Pirojpur Sadar",

  // Rangpur Division
  "Thakurgaon",
];

const bodyTypes = [
  "Slim",
  "Athletic",
  "Average",
  "Curvy",
  "Muscular",
  "Heavyset",
  // You can add more body types as needed
];

const meritalStatuses = ["Never Married", "Divorced", "Married"];
export {
  institutes,
  districts,
  meritalStatuses,
  cities,
  names,
  professions,
  marriageStatus,
  averageMonthlyIncomes,
  datesOfBirth,
  upazillas,
  skinColors,
  bodyTypes,
  sessions,
  educationTypes,
};
